### PR TITLE
[fix] parsing a field that holds array of arrays

### LINKED ISSUE #327: comma and bracket combined?
```
parse("foo[]=1,2,3&foo[]=4,5,6", {comma: true})
/*
expected { foo: [ [ 1, 2, 3 ], [4, 5, 6] ] }
received { foo: [ 1, 2, 3, 4, 5, 6 ] }

*/
```

uncertain if this is intentional or not

### PR DESCRIPTION
**Pull request by Om4ar**
fixes #327

### CODE REVIEW

File: lib/parse.js [hunk 1]
```diff
@@ -87,6 +87,10 @@ var parseValues = function parseQueryStringValues(str, options) {
             val = val.split(',');
         }
 
+        if(part.indexOf('[]=') > -1){
```
Comment (ljharb) [inline lib/parse.js]:
``` suggestion
        if (part.indexOf('[]=') > -1) {
```
what happens with `foo[][]=bar`, or just `[]=a`?

File: lib/parse.js [hunk 2]
```diff
@@ -87,6 +87,10 @@ var parseValues = function parseQueryStringValues(str, options) {
...
+          val = Array.isArray(val) ? [val] : val
```
Comment (ljharb) [inline lib/parse.js]: qs supports ES3, so we can't rely on `Array.isArray` being there

Comment (Om4ar) [reply lib/parse.js]: @ljharb 
replaced in utils
`var isArray = Array.isArray;` this is being used in the utils file
with
`var isArray = Object.prototype.toString.call(obj) === '[object Array]';`

File: lib/parse.js [hunk 3]
```diff
@@ -87,6 +87,10 @@ var parseValues = function parseQueryStringValues(str, options) {
             val = val.split(',');
         }
 
+        if (part.indexOf('[]=') > -1) {
+            val = utils.isArray(val) ? [val] : val;
```
Comment (ljharb) [inline lib/parse.js]: a perhaps simpler alternative here:
```suggestion
            val = [].concat([val]);
```

Comment (Om4ar) [reply lib/parse.js]: @ljharb 

`val = [].concat([val]);`

will fail test `allows disabling array parsing` in the following case:

```
        var emptyBrackets = qs.parse('a[]=b', { parseArrays: false });
        st.deepEqual(emptyBrackets, { a: { 0: 'b' } });
```
expected: |-
      { a: { 0: 'b' } }
    actual: |-
      { a: { 0: [ 'b' ] } }

File: lib/parse.js (hunk 1 above)
Comment (Om4ar) [reply lib/parse.js]: @ljharb 

`foo[][]=bar` will be parsed to ```{ foo: ['bar'] }```

`[]=a` will be parsed to  ```{ 0: 'a' }```

my code doesn't affect these results, it will be the same result

File: lib/parse.js (hunk 3 above)
Comment (ljharb) [reply lib/parse.js]: ah, right, `[].concat([val])` is actually just `[val]`, so that's not the same.

File: lib/utils.js [hunk 4]
```diff
@@ -1,7 +1,10 @@
 'use strict';
 
 var has = Object.prototype.hasOwnProperty;
-var isArray = Array.isArray;
```
Comment (ljharb) [inline lib/utils.js]: whoops, turns out we already depended on this being available ¯\\\_(ツ)_/¯

Comment (Om4ar) [reply lib/utils.js]: @ljharb  yes it is being used in stringify.js file too =D

Comment (Om4ar) [reply lib/utils.js]: @ljharb 
should i revert my changes on utils file and make another pr to replace Array.isArray by the polyfill ?

Comment (ljharb) [reply lib/utils.js]: nah for now just use Array.isArray the same way it's used in stringify.js.

Comment (Om4ar) [reply lib/utils.js]: okay, will revert my is changes for using this pollyfill
